package by.spetr.web.controller.command;

public enum CommandType {
    DEFAULT,
    ADD_NEW_MAKE_MODEL,
    ADD_NEW_MAKE,
    ADD_NEW_MODEL,
    GET_MAKE_MODEL_LIST,
    SHOW_USER_LIST_ADMIN,
    SHOW_VEHICLE_LIST,
    SHOW_VEHICLE_LIST_ADMIN,
    SHOW_VEHICLE_INFO,
    SHOW_VEHICLE_CREATION_PAGE,
    SHOW_MAKE_CREATION_PAGE,
    SHOW_MODEL_CREATION_PAGE,
    SHOW_MAKE_MODEL_CREATION_PAGE,
    UPDATE_VEHICLE_ADS,
    UPLOAD_VEHICLE_PHOTO,
    GO_TO_MAIN_PAGE,
    GO_TO_SIGN_UP_PAGE,
    CREATE_USER,
    SIGN_IN,
    LOG_OUT,
    CHANGE_LOCALE,
    CHANGE_USER_STATE,
    CHANGE_USER_ROLE,
    CHANGE_VEHICLE_STATE

}
