package by.spetr.web.command;

public enum CommandType {
    DEFAULT,
    SHOW_USER_LIST,
    SHOW_VEHICLE_LIST,
    SHOW_VEHICLE_INFO,
    SHOW_VEHICLE_ADS,
    GO_TO_SIGN_UP_PAGE,
    GO_TO_MAIN_PAGE,
    CREATE_USER_COMMAND,
    SIGN_IN_COMMAND,
    LOG_OUT_COMMAND,
    CHANGE_LOCALE,
    CHANGE_USER_STATE,
    CHANGE_USER_ROLE,
    CHANGE_VEHICLE_STATE
}
