package by.spetr.web.command;

public enum CommandType {
    DEFAULT,
    SHOW_USER_LIST,
    SHOW_VEHICLE_LIST,
    SHOW_VEHICLE_INFO,
    SHOW_VEHICLE_ADS,
    UPDATE_VEHICLE_ADS,
    UPLOAD_VEHICLE_PHOTO,
    GO_TO_SIGN_UP_PAGE,
    GO_TO_MAIN_PAGE,
    CREATE_USER,
    SIGN_IN,
    LOG_OUT,
    CHANGE_LOCALE,
    CHANGE_USER_STATE,
    CHANGE_USER_ROLE,
    CHANGE_VEHICLE_STATE
}
