<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>

<fmt:message key="main.title" var="main_title"/>
<fmt:message key="page.main" var="home"/>
<fmt:message key="page.main.greeting" var="main_greeting"/>
<fmt:message key="page.main.promotion" var="main_promotion"/>
<fmt:message key="page.main.step_0" var="main_step_0"/>
<fmt:message key="page.main.step_1" var="main_step_1"/>
<fmt:message key="page.main.step_2" var="main_step_2"/>
<fmt:message key="page.main.step_3" var="main_step_3"/>
<fmt:message key="page.main.step_4_1" var="main_step_4_1"/>
<fmt:message key="page.main.step_4_2" var="main_step_4_2"/>
<fmt:message key="page.main.step_4_3" var="main_step_4_3"/>
<fmt:message key="page.reg.greeting" var="reg_greeting"/>
<fmt:message key="page.reg.title" var="reg_title"/>
<fmt:message key="page.reg.promotion" var="reg_promotion"/>
<fmt:message key="page.req.terms_and_conditions" var="terms"/>
<fmt:message key="page.reg.username_req" var="username_req"/>
<fmt:message key="page.reg.pass_req" var="pass_req"/>
<fmt:message key="page.reg.passrepeat_req" var="passrep_req"/>
<fmt:message key="page.reg.email_req" var="email_req"/>
<fmt:message key="page.reg.phone_req" var="phone_req"/>
<fmt:message key="page.reg.terms_and_conditions_req" var="terms_req"/>
<fmt:message key="menu.show_user_list_adm" var="show_users"/>
<fmt:message key="menu.show_vehicle_list_adm" var="show_ads"/>
<fmt:message key="menu.show_message_list_adm" var="show_messages"/>
<fmt:message key="menu.add_make_model_adm" var="add_make_model"/>
<fmt:message key="menu.show_vehicle_list_personal" var="show_personal_ads"/>
<fmt:message key="page.make.title" var="make_title"/>
<fmt:message key="page.model.title" var="model_title"/>
<fmt:message key="page.color.title" var="color_title"/>
<fmt:message key="menu.drop_add_make" var="drop_make"/>
<fmt:message key="menu.drop_add_model" var="drop_model"/>
<fmt:message key="menu.drop_add_color" var="drop_color"/>
<fmt:message key="page.req.make_req" var="make_req"/>
<fmt:message key="page.req.model_req" var="model_req"/>
<fmt:message key="page.req.make_select_req" var="make_sel_req"/>
<fmt:message key="page.req.model_select_req" var="model_sel_req"/>
<fmt:message key="page.vehicle.fuel_req" var="fuel_sel_req"/>
<fmt:message key="page.vehicle.trans_req" var="trans_sel_req"/>
<fmt:message key="page.vehicle.drive_req" var="drive_sel_req"/>
<fmt:message key="page.vehicle.color_req" var="color_sel_req"/>
<fmt:message key="page.vehicle.model_year_req" var="model_year_req"/>
<fmt:message key="page.vehicle.displacement_req" var="displacement_req"/>
<fmt:message key="page.vehicle.mileage_req" var="mileage_req"/>
<fmt:message key="page.vehicle.power_req" var="power_req"/>
<fmt:message key="page.vehicle.price_req" var="price_req"/>
<fmt:message key="page.vehicle.photo_req" var="photo_req"/>
<fmt:message key="menu.place_new_ads" var="place"/>
<fmt:message key="page.create_vehicle.title" var="vhc_create_title"/>
<fmt:message key="page.create_vehicle.promotion" var="vhl_create_promo"/>
<fmt:message key="page.add_photo.title" var="vhl_add_photo_title"/>
<fmt:message key="page.add_photo.promo" var="vhl_add_photo_promo"/>
<fmt:message key="page.create_new_make_model_entry.title" var="vhc_create_make_model_title"/>
<fmt:message key="page.create_new_make" var="enter_new_make"/>
<fmt:message key="page.create_new_model" var="enter_new_model"/>
<fmt:message key="page.create_new_color" var="enter_new_color"/>
<fmt:message key="page.create_new_color_check" var="new_color_check"/>
<fmt:message key="global.vehicle_make" var="vehicle_make"/>
<fmt:message key="global.vehicle_model" var="vehicle_model"/>
<fmt:message key="user.login" var="login"/>
<fmt:message key="user.password" var="pass"/>
<fmt:message key="user.sign_in" var="sign_in"/>
<fmt:message key="user.sign_up" var="sign_up"/>
<fmt:message key="page.first_time" var="frst_time"/>
<fmt:message key="user.create" var="create"/>
<fmt:message key="user.log_out" var="log_out"/>
<fmt:message key="user.user" var="user_name"/>
<fmt:message key="user.role" var="role"/>
<fmt:message key="user.state" var="state"/>
<fmt:message key="user.ads" var="ads"/>
<fmt:message key="menu.show_vehicle_list_moder" var="ads_mod"/>
<fmt:message key="user.ads_full" var="ads_full"/>
<fmt:message key="user.sms" var="sms"/>
<fmt:message key="user.email" var="email"/>
<fmt:message key="user.phone" var="phone"/>
<fmt:message key="user.reg_date" var="reg_date"/>
<fmt:message key="global.message.entries" var="rec_found"/>
<fmt:message key="global.message.no_entries" var="no_rec_found"/>
<fmt:message key="page.main" var="home"/>
<fmt:message key="global.id" var="id"/>
<fmt:message key="global.disable" var="disable"/>
<fmt:message key="global.block" var="block"/>
<fmt:message key="global.enable" var="enable"/>
<fmt:message key="global.delete" var="delete"/>
<fmt:message key="global.delete_title" var="delete_title"/>
<fmt:message key="global.delete_description" var="delete_description"/>
<fmt:message key="global.cancel" var="cancel"/>
<fmt:message key="global.close" var="close"/>
<fmt:message key="global.close_title" var="close_title"/>
<fmt:message key="global.close_body" var="close_body"/>
<fmt:message key="global.edit" var="edit"/>
<fmt:message key="page.vehicle.state" var="state"/>
<fmt:message key="page.vehicle.owner" var="owner"/>
<fmt:message key="vehicle.characteristics" var="characteristics"/>
<fmt:message key="vehicle.select_make" var="select_make"/>
<fmt:message key="vehicle.select_model" var="select_model"/>
<fmt:message key="vehicle.select_fuel" var="select_fuel"/>
<fmt:message key="vehicle.select_trans" var="select_trans"/>
<fmt:message key="vehicle.select_drive" var="select_drive"/>
<fmt:message key="vehicle.select_color" var="select_color"/>
<fmt:message key="vehicle.enter_modelyear" var="enter_model_year"/>
<fmt:message key="vehicle.enter_displacement" var="enter_displacement"/>
<fmt:message key="vehicle.enter_mileage" var="enter_mileage"/>
<fmt:message key="vehicle.enter_power" var="enter_power"/>
<fmt:message key="vehicle.options_select" var="select_options_header"/>
<fmt:message key="vehicle.description" var="description_header"/>
<fmt:message key="vehicle.description_promo" var="description_promo"/>
<fmt:message key="vehicle.enter_description" var="enter_description"/>
<fmt:message key="vehicle.enter_price" var="enter_price"/>
<fmt:message key="vehicle.price" var="price_header"/>
<fmt:message key="vehicle.price_promo" var="price_promo"/>
<fmt:message key="page.select_photo" var="select_photo"/>
<fmt:message key="vehicle.photo" var="photos_header"/>
<fmt:message key="global.model_year" var="model_year"/>
<fmt:message key="global.mileage" var="mileage"/>
<fmt:message key="global.color" var="color"/>
<fmt:message key="global.price" var="price"/>
<fmt:message key="vehicle.id" var="lot_id"/>
<fmt:message key="vehicle.powertrain" var="powertrain"/>
<fmt:message key="vehicle.transmission" var="transmission"/>
<fmt:message key="vehicle.drive" var="drive"/>
<fmt:message key="vehicle.displacement" var="displacement"/>
<fmt:message key="vehicle.displacement_cc" var="cc"/>
<fmt:message key="vehicle.power" var="power"/>
<fmt:message key="vehicle.power_hp" var="hp"/>
<fmt:message key="vehicle.creation_date" var="creation_date"/>
<fmt:message key="vehicle.options" var="v_options"/>
<fmt:message key="vehicle.comments" var="comments"/>
<fmt:message key="vehicle.info" var="info"/>
<fmt:message key="global.message.entries" var="entries"/>
<fmt:message key="global.message.no_entries" var="no_entries"/>
<fmt:message key="page.global.about" var="about"/>
<fmt:message key="regexp.phone" var="regexp_phone"/>
<fmt:message key="regexp.username" var="regexp_username"/>
<fmt:message key="regexp.email" var="regexp_email"/>
<fmt:message key="error.login_taken" var="login_"/>
<fmt:message key="user.email" var="email"/>
<fmt:message key="user.password_repeat" var="pass_rep"/>
<fmt:message key="user.phone" var="phone"/>
<fmt:message key="user.create" var="create"/>
<fmt:message key="error.error_title" var="error"/>
<fmt:message key="regexp.email" var="email_regexp"/>
<fmt:message key="regexp.password" var="password_regexp"/>
<fmt:message key="regexp.vehicle_model_year" var="model_year_regexp"/>
<fmt:message key="regexp.vehicle_displacement" var="displacement_regexp"/>
<fmt:message key="regexp.vehicle_mileage" var="mileage_regexp"/>
<fmt:message key="regexp.vehicle_power" var="power_regexp"/>
<fmt:message key="regexp.vehicle_price" var="price_regexp"/>